apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::796853572186:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-C1ZYP4IIVSHK
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-10T14:44:21Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-10T14:44:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1585"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4f9bfa84-d354-4fb8-89f6-df9d1ac525a2
